// app/layout.tsx
import { Metadata } from 'next';
import './globals.css';
import { Manrope } from 'next/font/google';
import { Navbar } from './ui/navBar';
import Footer from './ui/footer';

const manrope = Manrope({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <header>
          <Navbar />
        </header>
        {children}
        <Footer />
      </body>
    </html>
  );
}
